#file: noinspection SpringBootApplicationYaml
server:
  port: ${RECEIVER_APP_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

telegram:
  token: ${TELEGRAM_BOT_TOKEN}

rabbit:
  updates-topic-name: ${RABBIT_UPDATES_TOPIC_NAME:updates-queue}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: vhost

logging:
  level:
    org.apache.kafka: warn
    ru.tbank.receiver: debug
