#file: noinspection SpringBootApplicationYaml
server:
  port: ${RECEIVER_APP_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

telegram:
  token: ${TELEGRAM_BOT_TOKEN}

rabbit:
  exchange-name: updates-exchange
  group-updates-queue-name: group-updates-queue
  group-updates-queue-key: queue.group
  personal-updates-queue-name: personal-updates-queue
  personal-updates-queue-key: queue.personal

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: vhost

logging:
  level:
    org.apache.kafka: warn
    ru.tbank.receiver: debug
