#file: noinspection SpringBootApplicationYaml
telegram:
    token: ${TELEGRAM_BOT_TOKEN}

kafka:
  updates-topic: ${KAFKA_UPDATES_TOPIC_NAME:updates-queue}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.apache.kafka: warn
    ru.tbank.receiver: debug