#file: noinspection SpringBootApplicationYaml
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}

mq:
  updates-topic-name: ${KAFKA_UPDATES_TOPIC_NAME:updates-queue}

spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "org.telegram.telegrambots.meta.api.objects"

logging:
  level:
    org.apache.kafka: warn