server:
  port: ${PROCESSOR_APP_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

telegram:
  token: ${TELEGRAM_BOT_TOKEN}
  bot-addition-url: https://t.me/%s?startgroup&admin=promote_members+delete_messages+restrict_members
  owner-id: ${OWNER_ACCOUNT_ID}

rabbit:
  updates-topic-name: ${RABBIT_UPDATES_TOPIC_NAME:updates-queue}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: vhost

redis:
  master:
    host: ${REDIS_MASTER_HOST:localhost}
    port: 6379
  slaves:
    - host: ${REDIS_SLAVE_1_HOST:localhost}
      port: 7000
    - host: ${REDIS_SLAVE_2_HOST:localhost}
      port: 7001
  chat-configs-db: 0
  users-state-db: 1

logging:
  level:
    ru.tbank.processor: debug
    org.jooq: warn

password-generator:
  password-length: 8
