services:
  db:
    image: postgres:16.4-alpine
    container_name: $POSTGRES_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 10



  admin-panel:
    build: ./admin-panel
    container_name: $ADMIN_PANEL_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${ADMIN_PANEL_HTTP_PORT}:8080"
    environment:
      ADMIN_PANEL_JWT_SECRET: $ADMIN_PANEL_JWT_SECRET
      POSTGRES_CONTAINER_NAME: $POSTGRES_CONTAINER_NAME
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      db:
        condition: service_healthy