scrape_configs:
  - job_name: 'ProcessorService'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'Chat Protector processor service'

  - job_name: 'ReceiverService'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Chat Protector receiver service'

  - job_name: 'AdminService'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'Chat Protector admin service'

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['host.docker.internal:9093']