telegram:
  bot:
    token: ${BOT_TOKEN}

gigachat:
  system-prompt: ${GIGACHAT_SYSTEM_PROMPT}
  auth-data: ${GIGACHAT_AUTH_DATA}
  scope: ${GIGACHAT_SCOPE}
  chat-uri: ${GIGACHAT_CHAT_URI}
  auth-uri: ${GIGACHAT_AUTH_URI}