telegram:
  bot:
    token: ${BOT_TOKEN}

gigachat:
  system-prompt: ${GIGACHAT_SYSTEM_PROMPT}
  auth-data: ${GIGACHAT_AUTH_DATA}
  scope: ${GIGACHAT_SCOPE}
  chat-uri: ${GIGACHAT_CHAT_URI}
  auth-uri: ${GIGACHAT_AUTH_URI}

yandex-cloud:
  authorized-key-filename: "C:\\Users\\Aleksey\\IdeaProjects\\chat-protector\\src\\main\\resources\\yandex-cloud-configs\\text-classification.json"
  auth-url: https://iam.api.cloud.yandex.net/iam/v1/tokens
  folder-id: b1g8qadjase8qifkgpq2
  text-classification-url: https://llm.api.cloud.yandex.net/foundationModels/v1/fewShotTextClassification


spring:
  profiles:
    active:
      - yandex-gpt