{
 "title": "Chat Protector",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Время обработки обновлений в личных чатах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(personalMessageProcessing_seconds_sum[1m]) / increase(personalMessageProcessing_seconds_count[1m])",
     "legendFormat": "Время обработки, с"
    }
   ]
  },
  {
   "title": "Число обновлений от Telegram в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(telegramApiUpdate_seconds_count[1m])) * 60",
     "legendFormat": "Число обновлений, n"
    }
   ]
  },
  {
   "title": "Время обработки обновлений в групповых чатах",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(groupMessageProcessing_seconds_sum[1m]) / increase(groupMessageProcessing_seconds_count[1m])",
     "legendFormat": "Время обработки, с"
    }
   ]
  }
 ]
}