#file: noinspection SpringBootApplicationYaml
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

redis:
  master:
    host: ${REDIS_MASTER_HOST:localhost}
    port: 6379
  slaves:
    - host: ${REDIS_SLAVE_1_HOST:localhost}
      port: 7000
    - host: ${REDIS_SLAVE_2_HOST:localhost}
      port: 7001
  chat-configs-db: 0

jwt:
  secret: ${ADMIN_SERVICE_JWT_SECRET:J6GOtcwC2NJI1l0VkHu20PacPFGTxpirBxWwynoHjsc=}
  ttl: 3600 # in seconds

logging:
  level:
    org.jooq: warn

api:
  version: 1.0.1
  description: С помощью этого API Вы можете получить историю удалённых сообщений в конкретном чате, а также
    настраивать фильтры модерации в чатах
  title: API Админ панели системы Chat Protector
  server:
    url: http://localhost:8080
