server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  mustache:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

redis:
  master:
    host: ${REDIS_MASTER_HOST:localhost}
    port: 6379
  slaves:
    - host: ${REDIS_SLAVE_1_HOST:localhost}
      port: 7000
    - host: ${REDIS_SLAVE_2_HOST:localhost}
      port: 7001
  chat-configs-db: 0
  users-state-db: 1

jwt:
  secret: ${ADMIN_SERVICE_JWT_SECRET}
  ttl: 3600 # in seconds