# noinspection ComposeUnknownKeys
include:
  - compose-network.yml

services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    networks:
      - app-tier
    ports:
      - '9090:9090'
    volumes:
      - ../../metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    networks:
      - app-tier
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../../metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  prometheus:
    name: prometheus
    driver: local
