include:
  - compose-environment.yml

services:
  admin-service:
    build:
      context: ../..
      dockerfile: docker/admin-service.Dockerfile
    container_name: admin-service
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:8080'
    environment:
      ADMIN_PANEL_JWT_SECRET: $ADMIN_SERVICE_JWT_SECRET
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: postgres
      REDIS_MASTER_HOST: redis-master
      REDIS_SLAVE_1_HOST: redis-slave-1
      REDIS_SLAVE_2_HOST: redis-slave-2
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis-master:
        condition: service_healthy

  update-receiver:
    build:
      context: ../..
      dockerfile: docker/update-receiver.Dockerfile
    container_name: update-receiver
    ports:
      - '8081:8081'
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      RABBIT_UPDATES_TOPIC_NAME: $RABBIT_UPDATES_TOPIC_NAME
      TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      liquibase:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy

  update-processor:
    build:
      context: ../..
      dockerfile: docker/update-processor.Dockerfile
    container_name: update-processor
    ports:
      - '8082:8082'
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      RABBIT_UPDATES_TOPIC_NAME: $RABBIT_UPDATES_TOPIC_NAME
      TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
      REDIS_MASTER_HOST: redis-master
      REDIS_SLAVE_1_HOST: redis-slave-1
      REDIS_SLAVE_2_HOST: redis-slave-2
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      liquibase:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
      redis-master:
        condition: service_healthy
