include:
  - compose-network.yml

services:
  alertmanager:
    build:
      context: ../..
      dockerfile: ./docker/alertmanager/alertmanager.Dockerfile
    container_name: alertmanager
    env_file: .env
    environment:
      TELEGRAM_ALERT_BOT_TOKEN: $TELEGRAM_ALERT_BOT_TOKEN
      TELEGRAM_OWNER_ACCOUNT_ID: $TELEGRAM_OWNER_ACCOUNT_ID
    networks:
      - app-tier
    volumes:
      - ../../metrics/alertmanager/config/telegram.tmpl:/etc/alertmanager/telegram.tmpl
    ports:
      - '9093:9093'

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    networks:
      - app-tier
    ports:
      - '9090:9090'
    volumes:
      - ../../metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../../metrics/prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    networks:
      - app-tier
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../../metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../../metrics/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../../grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus:
    name: prometheus
    driver: local
