# noinspection ComposeUnknownKeys
include:
  - compose-environment.yml

services:
  admin-service:
    build:
      context: ../..
      dockerfile: docker/admin-service.Dockerfile
    container_name: admin-service
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    ports:
      - '8080:8080'
    environment:
      ADMIN_PANEL_JWT_SECRET: $ADMIN_SERVICE_JWT_SECRET
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: postgres
      REDIS_MASTER_HOST: redis-master
      REDIS_SLAVE_1_HOST: redis-slave-1
      REDIS_SLAVE_2_HOST: redis-slave-2
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis-master:
        condition: service_healthy

  update-receiver:
    build:
      context: ../..
      dockerfile: docker/update-receiver.Dockerfile
    container_name: update-receiver
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    environment:
      KAFKA_UPDATES_TOPIC_NAME: $KAFKA_UPDATES_TOPIC_NAME
      TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      liquibase:
        condition: service_completed_successfully
      init-kafka:
        condition: service_completed_successfully

  update-processor:
    build:
      context: ../..
      dockerfile: docker/update-processor.Dockerfile
      args:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: $POSTGRES_PORT
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      network: host
    container_name: update-processor
    networks:
      - app-tier
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: postgres
      KAFKA_UPDATES_TOPIC_NAME: $KAFKA_UPDATES_TOPIC_NAME
      TELEGRAM_BOT_TOKEN: $TELEGRAM_BOT_TOKEN
      REDIS_MASTER_HOST: redis-master
      REDIS_SLAVE_1_HOST: redis-slave-1
      REDIS_SLAVE_2_HOST: redis-slave-2
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      liquibase:
        condition: service_completed_successfully
      init-kafka:
        condition: service_completed_successfully
      redis-master:
        condition: service_healthy
