services:
  kafka:
    image: &kafka-image bitnami/kafka:3.8
    env_file: .env
    container_name: $KAFKA_CONTAINER_NAME
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_NUM_PARTITIONS: 1
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list" ]
      start_period: 15s
      interval: 3s
      timeout: 5s
    networks:
      - backend

  init-kafka:
    image: *kafka-image
    container_name: init-kafka
    working_dir: /opt/bitnami/kafka/bin
    entrypoint: /bin/bash
    env_file: .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend
    command: |
      -c "
      kafka-topics.sh --create --if-not-exists --topic $${KAFKA_UPDATES_TOPIC_NAME} --bootstrap-server kafka:9092
      kafka-topics.sh --describe --bootstrap-server kafka:9092
      "

  redis:
    env_file: .env
    container_name: $REDIS_CONTAINER_NAME
    image: redis:7.4.1
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      timeout: 5s
    networks:
      - backend

  postgres:
    image: postgres:17
    env_file: .env
    container_name: $POSTGRES_CONTAINER_NAME
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
    networks:
      - backend

  liquibase:
    image: liquibase:4.29.2
    container_name: liquibase
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "--url=jdbc:postgresql://${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}",
      "--username=${POSTGRES_USER}",
      "--password=${POSTGRES_PASSWORD}",
      "--search-path=/liquibase/changelog/",
      "--driver=org.postgresql.Driver",
      "--changeLogFile=db-changelog.yml",
      "update"
    ]
    volumes:
      - ../../migrations/db/changelog:/liquibase/changelog/
    networks:
      - backend

networks:
  backend: { }