name: Admin service module workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - 'admin-service/**'
      - 'common/**'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate jOOQ classes
        run: ./gradlew :admin-service:jooqCodegen

      - name: Build with Gradle
        run: ./gradlew :admin-service:bootJar

  integration-testing:
    needs:
      - build
    runs-on: ubuntu-latest
    name: Integration Testing
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate jOOQ classes
        run: ./gradlew :admin-service:jooqCodegen :update-processor:jooqCodegen

      - name: Run tests
        run: ./gradlew :admin-service:test

  package:
    needs:
      - integration-testing
    runs-on: ubuntu-latest
    name: Package
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate jOOQ classes
        run: ./gradlew :admin-service:jooqCodegen

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/admin-service.Dockerfile
          push: true
          tags: ghcr.io/ghostofendless/admin-service:latest
