name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  package:
    runs-on: ubuntu-latest
    name: Package
    permissions:
      packages: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/admin-service.Dockerfile
          push: true
          tags: ghcr.io/ghostofendless/admin-service:latest