name: Measure coverage

on:
  workflow_run:
    workflows:
      - Admin service module workflow
      - Update processor module workflow
      - Update receiver module workflow
    types:
      - completed
  pull_request:
    branches:
      - master
    paths:
      - 'admin-service/**'
      - 'update-receiver/**'
      - 'update-processor/**'
      - 'common-telegram/**'
      - 'common/**'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  measure-coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Generate coverage message
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
